### PR TITLE
overriden alter column type macro

### LINKED ISSUE #77: Incremental materialization strategy delete+insert fails when one of the previous records was updated
### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?
dbt run
After running an incremental model (delete+insert strategy) on a delta on original data, where some data points where updated.
The following error is shown
Database Error in model all_orders (models\core\all_orders.sql)
13:25:49    [Version 17.20.0.19] [Session 2702] [Teradata Database] [Error 3707] Syntax error, expected something like '(' between the 'column' keyword and 
the word 'order_status__dbt_alter'.

Notice that the table dbt_alter is a dbt-teradata connector generated table not a table generated through user defined models.

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

1. Clone this repository: [https://github.com/Teradata/teddy_retailers_dbt-dev/](url)
2. Create the teddy_retailers database in your vantage instance (created through ClearScape Analytics Experience due to NOS compatibility)
3. Run the following script in your vantage instance
`CREATE SET TABLE teddy_retailers.source_products AS
(
  SELECT *
    FROM (
		LOCATION='/gs/storage.googleapis.com/clearscape_analytics_demo_data/DEMO_dbtAdvanced/raw_products.csv') as products
) WITH DATA;
CREATE SET TABLE teddy_retailers.source_customers AS
(
  SELECT *
    FROM (
		LOCATION='/gs/storage.googleapis.com/clearscape_analytics_demo_data/DEMO_dbtAdvanced/raw_customers.csv') as customers
) WITH DATA;
CREATE SET TABLE teddy_retailers.source_orders AS
(
  SELECT *
    FROM (
		LOCATION='/gs/storage.googleapis.com/clearscape_analytics_demo_data/DEMO_dbtAdvanced/primary_orders_first.csv') as orders
) WITH DATA;
CREATE SET TABLE teddy_retailers.source_order_products AS
(
  SELECT order_id, product_id, product_quantity
    FROM (
		LOCATION='/gs/storage.googleapis.com/clearscape_analytics_demo_data/DEMO_dbtAdvanced/primary_order_products_first.csv') as orders_products
) WITH DATA;`

4. cd to the cloned repository and execute dbt_run
5. Update the data sources for the models with the following script
`drop table teddy_retailers.source_orders;
CREATE SET TABLE teddy_retailers.source_orders AS
(
  SELECT *
    FROM (
		LOCATION='/gs/storage.googleapis.com/clearscape_analytics_demo_data/DEMO_dbtAdvanced/primary_orders_second.csv') as orders
) WITH DATA;
drop table teddy_retailers.source_order_products;
CREATE SET TABLE teddy_retailers.source_order_products AS
(
  SELECT order_id, product_id, product_quantity
    FROM (
		LOCATION='/gs/storage.googleapis.com/clearscape_analytics_demo_data/DEMO_dbtAdvanced/primary_order_products_second.csv') as orders_products
) WITH DATA;`

6. Execute dbt run once again.

### Expected behavior
The incremental model should run correctly without erroring due to syntax errors in internal generated commands.

### Screenshots and log output
`alter table "teddy_retailers"."all_orders" add column "order_status__dbt_alter" character varying(17);
    update "teddy_retailers"."all_orders" set "order_status__dbt_alter" = "order_status";
    alter table "teddy_retailers"."all_orders" drop column "order_status" cascade;
    alter table "teddy_retailers"."all_orders" rename column "order_status__dbt_alter" to "order_status"
  
[0m13:19:22.240566 [debug] [Thread-1 (]: teradata adapter: Teradata error: [Version 17.20.0.19] [Session 2678] [Teradata Database] [Error 3707] Syntax error, expected something like '(' between the 'column' keyword and the word 'order_status__dbt_alter'.
 at gosqldriver/teradatasql.formatError ErrorUtil.go:89`

**The output of `dbt --version`:**
```
1.3.3
```

**The operating system you're using:**

Windows 10

**The output of `python --version`:**

3.10

### PR DESCRIPTION
**Pull request by VarunSharma15**
resolves #77 

### Description

Problem was with one of the macro which has slightly different syntax than Teradata syntax.
So overridden the macro with correct syntax.

### Checklist
 - [ ] I have run this code in development and it appears to resolve the stated issue
 - [ ] This PR includes tests, or tests are not required/relevant for this PR
 - [ ] I have updated the `CHANGELOG.md` with information about my change

### CODE REVIEW

**Comment by VarunSharma15** [comment]
Before fix :
before_fix


After fix :
 After_fix

File: dbt/include/teradata/macros/columns.sql [hunk 1]
```diff
@@ -0,0 +1,29 @@
+{% macro teradata__alter_column_type(relation, column_name, new_column_type) -%}
```
Comment (adamtwo) [inline dbt/include/teradata/macros/columns.sql:1]: I think it would be useful to add a comment that explains why this macro needs an override.

**Review by adamtwo — CHANGES_REQUESTED** [review]
Thanks for looking into this. I've 2 remarks:
1. Could you please add an explanation in the macro file why the macro requires an override?
2. Could you please add a test that fails without the change, but passes with the change?

File: dbt/include/teradata/macros/columns.sql [hunk 2]
```diff
@@ -1,3 +1,8 @@
+/* This macro is used when there is mismatch in column types from source while incremental modelling.
+For e.g We had a incremental run already for a project and later some user came and played with column type of 
+one of the column of the source and changed it e.g from varchar(20) changed it to varchar(25)
+So to sync up the data types this macro comes into play.
+*/
```
Comment (adamtwo) [inline dbt/include/teradata/macros/columns.sql:5]: Sorry, I didn't mean to suggest that we should explain why dbt has this macro. IMO, we only should explain why we need to override the default implementation.

```suggestion
/* The macro had to be overridden for Teradata because original macro uses `column` keyword that is not supported nor needed in Teradata's `ALTER TABLE` syntax.
*/
```

Comment (VarunSharma15) [reply dbt/include/teradata/macros/columns.sql:5]: Sorry, I misinterpreted.
Sure, will change the comment and have added the testcase for the same.

**Review by adamtwo — APPROVED** [review]
