### PR TITLE
Collisions in dbt_scd_id while calculating snapshots bug

### LINKED ISSUE #160: Collisions in dbt_scd_id while calculating snapshots
### Describe the bug
The snapshot calculation relies on the Teradata HASHROW function. The `dbt_scd_id` is generated for each row based on the provided `unique_key` and the current timestamp. However, the HASHROW function produces a 4-byte hash, which is highly prone to collisions. For instance, the values `d3dadd49420542fb49ffbf6a77349b45` and `34f325fe5a4216f27357328b61c9eccb` both produce the same hash `02-27-E3-B4`. Similarly, the numbers `162181727` and `880145039` generate the same hash `2E-5B-FE-DD`. In a source with 36 million numbers, we have over 180 thousand duplicate dbt_scd_id.

These collisions cause the snapshot update to fail with the error: [Error 7547] Target row updated by multiple source rows.

### Steps To Reproduce
Create a source with the provided values as IDs and then try to create a snapshot of them.

### Expected behavior
Calculating the snapshot without errors.

### Screenshots and log output

**The output of `dbt --version`:**
```
Core:
  - installed: 1.7.11
  - latest:    1.8.0  - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - teradata: 1.7.2 - Up to date!
```

**The operating system you're using:**
Windows 11

**The output of `python --version`:**
Python 3.11.3

### PR DESCRIPTION
**Pull request by tallamohan**
resolves #160

### CODE REVIEW

File: dbt/include/teradata/macros/materializations/snapshot/strategies.sql [hunk 1]
```diff
@@ -1,6 +1,6 @@
 
 {% macro teradata__snapshot_hash_arguments(args) -%}
-    HASHROW({%- for arg in args -%}
+    GLOBAL_FUNCTIONS.hash_md5({%- for arg in args -%}
```
Comment (rafaelkrysciak) [inline dbt/include/teradata/macros/materializations/snapshot/strategies.sql:3]: I suggest using the `dbt.hash` macro since the md5 function is configured differently in every environment.

Comment (septimit) [reply dbt/include/teradata/macros/materializations/snapshot/strategies.sql:3]: This would also require dbt.hash to be configurable. One proposal on how to do that can be found here: https://github.com/Teradata/dbt-teradata-utils/issues/2

Comment (rafaelkrysciak) [reply dbt/include/teradata/macros/materializations/snapshot/strategies.sql:3]: Regrettably, our `md5` implementation differs from the standard. Therefore, in our project, we have developed our own `teradata__hash` macro to align with the database configuration. Consequently, to accommodate this modification, we will also need to create a distinct implementation of `teradata__snapshot_hash_arguments` to cater to the custom `md5` setup.

**Comment by tallamohan** [comment]
@rafaelkrysciak and @septimit we are modifying this implementation.
Adding a new configuration option at the profile level and at the model level to provide the custom database name and UDF name.

File: README.md [hunk 2]
```diff
@@ -487,6 +487,23 @@ Seeds, in addition to the above materialization modifiers, have the following op
       <project-name>:
         +use_fastload: true
     ```
+#### Snapshots
+Snapshots uses the HASHROW function of the Teradata database to generate a unique hash value for the 'dbt_scd_id' column. If you want to use your own hash UDF, there is a configuration option in the snapshot model called 'snapshot_hash_udf', which defaults to HASHROW. You can provide a value like <database_name.hash_udf_name>. If only hash_udf_name is provided, it uses the same schema as the model runs.
+
+for e.g. :
+  snapshots/snapshot_example.yml
```
Comment (VarunSharma15) [inline README.md:494]: The below example seems to be the .sql file, not .yml
Can you please alter that?
One more question, will users be able to provide snapshot_hash_udf configuration from .yml files as well ? for example schema.yml or dbt_project.yml?

Comment (tallamohan) [reply README.md:494]: Corrected. Changed to .sql
No, user can only can use this configuration in the snapshot model sql.

**Review by VarunSharma15 — APPROVED** [review]
Looks Good to me
